service: incident-report-generator
image: zonebrite/incident-report-generator

servers:
    web:
        hosts:
            - "%{SERVER_IP}"

proxy:
    host: incidents.zonebrite.com
    app_port: 8000

registry:
    username: zonebrite
    password:
        - KAMAL_REGISTRY_PASSWORD

builder:
    dockerfile: Dockerfile

volumes:
    - "incident-temp:/app/temp"
