service: incident-report-generator
image: zonebrite/incident-report-generator

servers:
    web:
        - 164.92.73.163

proxy:
    host: incidents.zonebrite.com
    app_port: 8000

registry:
    username: zonebrite
    password:
        - KAMAL_REGISTRY_PASSWORD

builder:
    arch: amd64
    dockerfile: Dockerfile

ssh:
    user: zonebrite
    keys:
        - ~/.ssh/zonebrite

volumes:
    - "incident-temp:/app/temp"
